apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app:  helloworld
    spec:
      containers:
      - name: my-python-image
        image: arjunachari12/k8s-demo
        ports:
        - name: nodejs-post
          containerPort: 3000
