apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - name: nginx-partha
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: afakharany-partha
    image: afakharany/watcher:latest
