apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: python-controller
  labels:
    app: python-new
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python-new
  template:
    metadata:
      labels:
        app: python-new
    spec:
      containers:
      - name: my-python-image
        image: arjunachari12/my-python-image
