apiVersion: v1
kind: Pod
metadata:
  name: secret-test
spec:
  containers:
    - name: mysql-container
      image: mysql:5.6
      env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
      volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /etc/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
